python -m textureatlas -o atlas.png -m atlas.map -mf binary^
 "assets/cursor/mouse_cursor_point.png" "assets/cursor/mouse_cursor_hover.png"^
 "assets/icons/solar_icon.png" "assets/robots/solar/solar_off.png" "assets/icons/shooter_icon.png" "assets/robots/shooter/shooter_off.png" "assets/icons/lasertron_icon.png" "assets/robots/lasertron/lasertron_off.png" "assets/icons/catapult_icon.png" "assets/robots/catapult/catapult_off.png"^
 b1_alien_walk="assets/aliens/b1/walk/b1_alien_walk_frame0.png assets/aliens/b1/walk/b1_alien_walk_frame1.png assets/aliens/b1/walk/b1_alien_walk_frame2.png assets/aliens/b1/walk/b1_alien_walk_frame3.png"^
 b2_alien_walk="assets/aliens/b2/walk/b2_alien_walk_frame0.png assets/aliens/b2/walk/b2_alien_walk_frame1.png assets/aliens/b2/walk/b2_alien_walk_frame2.png assets/aliens/b2/walk/b2_alien_walk_frame3.png"^
 b1_alien_death="assets/aliens/b1/death/b1_alien_death_frame0.png assets/aliens/b1/death/b1_alien_death_frame1.png assets/aliens/b1/death/b1_alien_death_frame2.png assets/aliens/b1/death/b1_alien_death_frame3.png assets/aliens/b1/death/b1_alien_death_frame4.png assets/aliens/b1/death/b1_alien_death_frame5.png assets/aliens/b1/death/b1_alien_death_frame6.png assets/aliens/b1/death/b1_alien_death_frame7.png assets/aliens/b1/death/b1_alien_death_frame8.png"^
 b2_alien_death="assets/aliens/b2/death/b2_alien_death_frame0.png assets/aliens/b2/death/b2_alien_death_frame1.png assets/aliens/b2/death/b2_alien_death_frame2.png assets/aliens/b2/death/b2_alien_death_frame3.png assets/aliens/b2/death/b2_alien_death_frame4.png assets/aliens/b2/death/b2_alien_death_frame5.png assets/aliens/b2/death/b2_alien_death_frame6.png assets/aliens/b2/death/b2_alien_death_frame7.png assets/aliens/b2/death/b2_alien_death_frame8.png"^
 b1_alien_attack="assets/aliens/b1/attack/b1_alien_attack_frame0.png assets/aliens/b1/attack/b1_alien_attack_frame1.png assets/aliens/b1/attack/b1_alien_attack_frame2.png assets/aliens/b1/attack/b1_alien_attack_frame3.png assets/aliens/b1/attack/b1_alien_attack_frame4.png assets/aliens/b1/attack/b1_alien_attack_frame5.png assets/aliens/b1/attack/b1_alien_attack_frame6.png"^
 b2_alien_attack="assets/aliens/b2/attack/b2_alien_attack_frame0.png assets/aliens/b2/attack/b2_alien_attack_frame1.png assets/aliens/b2/attack/b2_alien_attack_frame2.png assets/aliens/b2/attack/b2_alien_attack_frame3.png assets/aliens/b2/attack/b2_alien_attack_frame4.png"^
 solar_idle="assets/robots/solar/idle/solar_idle_frame00.png assets/robots/solar/idle/solar_idle_frame01.png assets/robots/solar/idle/solar_idle_frame02.png assets/robots/solar/idle/solar_idle_frame03.png assets/robots/solar/idle/solar_idle_frame04.png assets/robots/solar/idle/solar_idle_frame05.png  assets/robots/solar/idle/solar_idle_frame06.png assets/robots/solar/idle/solar_idle_frame07.png assets/robots/solar/idle/solar_idle_frame08.png assets/robots/solar/idle/solar_idle_frame09.png assets/robots/solar/idle/solar_idle_frame10.png assets/robots/solar/idle/solar_idle_frame11.png assets/robots/solar/idle/solar_idle_frame12.png assets/robots/solar/idle/solar_idle_frame13.png  assets/robots/solar/idle/solar_idle_frame14.png assets/robots/solar/idle/solar_idle_frame15.png assets/robots/solar/idle/solar_idle_frame16.png assets/robots/solar/idle/solar_idle_frame17.png assets/robots/solar/idle/solar_idle_frame18.png assets/robots/solar/idle/solar_idle_frame19.png assets/robots/solar/idle/solar_idle_frame20.png assets/robots/solar/idle/solar_idle_frame21.png assets/robots/solar/idle/solar_idle_frame22.png  assets/robots/solar/idle/solar_idle_frame23.png assets/robots/solar/idle/solar_idle_frame24.png assets/robots/solar/idle/solar_idle_frame25.png assets/robots/solar/idle/solar_idle_frame26.png assets/robots/solar/idle/solar_idle_frame27.png assets/robots/solar/idle/solar_idle_frame28.png assets/robots/solar/idle/solar_idle_frame29.png assets/robots/solar/idle/solar_idle_frame30.png assets/robots/solar/idle/solar_idle_frame31.png assets/robots/solar/idle/solar_idle_frame32.png assets/robots/solar/idle/solar_idle_frame33.png"^
 shooter_idle="assets/robots/shooter/idle/shooter_idle_frame0.png assets/robots/shooter/idle/shooter_idle_frame1.png assets/robots/shooter/idle/shooter_idle_frame2.png assets/robots/shooter/idle/shooter_idle_frame3.png"^
 shooter_shoot="assets/robots/shooter/shoot/shooter_shoot_frame0.png assets/robots/shooter/shoot/shooter_shoot_frame1.png assets/robots/shooter/shoot/shooter_shoot_frame2.png assets/robots/shooter/shoot/shooter_shoot_frame3.png assets/robots/shooter/shoot/shooter_shoot_frame4.png assets/robots/shooter/shoot/shooter_shoot_frame5.png assets/robots/shooter/shoot/shooter_shoot_frame6.png assets/robots/shooter/shoot/shooter_shoot_frame7.png"^
 lasertron_idle="assets/robots/lasertron/idle/lasertron_idle_frame0.png assets/robots/lasertron/idle/lasertron_idle_frame1.png assets/robots/lasertron/idle/lasertron_idle_frame2.png assets/robots/lasertron/idle/lasertron_idle_frame3.png"^
 lasertron_shoot="assets/robots/lasertron/shoot/lasertron_shoot_frame00.png assets/robots/lasertron/shoot/lasertron_shoot_frame01.png assets/robots/lasertron/shoot/lasertron_shoot_frame02.png assets/robots/lasertron/shoot/lasertron_shoot_frame03.png assets/robots/lasertron/shoot/lasertron_shoot_frame04.png assets/robots/lasertron/shoot/lasertron_shoot_frame05.png assets/robots/lasertron/shoot/lasertron_shoot_frame06.png assets/robots/lasertron/shoot/lasertron_shoot_frame07.png assets/robots/lasertron/shoot/lasertron_shoot_frame08.png assets/robots/lasertron/shoot/lasertron_shoot_frame09.png assets/robots/lasertron/shoot/lasertron_shoot_frame10.png assets/robots/lasertron/shoot/lasertron_shoot_frame11.png"^
 catapult_idle="assets/robots/catapult/idle/catapult_idle_frame0.png assets/robots/catapult/idle/catapult_idle_frame1.png assets/robots/catapult/idle/catapult_idle_frame2.png assets/robots/catapult/idle/catapult_idle_frame3.png"^
 catapult_shoot="assets/robots/catapult/shoot/catapult_shoot_frame0.png assets/robots/catapult/shoot/catapult_shoot_frame1.png assets/robots/catapult/shoot/catapult_shoot_frame2.png assets/robots/catapult/shoot/catapult_shoot_frame3.png assets/robots/catapult/shoot/catapult_shoot_frame4.png assets/robots/catapult/shoot/catapult_shoot_frame5.png assets/robots/catapult/shoot/catapult_shoot_frame6.png"^
 portal_alien_walk="assets/aliens/portal/walk/portal_alien_walk_frame0.png assets/aliens/portal/walk/portal_alien_walk_frame1.png assets/aliens/portal/walk/portal_alien_walk_frame2.png assets/aliens/portal/walk/portal_alien_walk_frame3.png assets/aliens/portal/walk/portal_alien_walk_frame4.png"^
 portal_alien_death="assets/aliens/portal/death/portal_alien_death_frame0.png assets/aliens/portal/death/portal_alien_death_frame1.png assets/aliens/portal/death/portal_alien_death_frame2.png assets/aliens/portal/death/portal_alien_death_frame3.png assets/aliens/portal/death/portal_alien_death_frame4.png assets/aliens/portal/death/portal_alien_death_frame5.png assets/aliens/portal/death/portal_alien_death_frame6.png"^
 portal_alien_attack="assets/aliens/portal/attack/portal_alien_attack_frame0.png assets/aliens/portal/attack/portal_alien_attack_frame1.png assets/aliens/portal/attack/portal_alien_attack_frame2.png assets/aliens/portal/attack/portal_alien_attack_frame3.png assets/aliens/portal/attack/portal_alien_attack_frame4.png"^
 portal_alien_summon="assets/aliens/portal/summon/portal_alien_summon_frame0.png assets/aliens/portal/summon/portal_alien_summon_frame1.png assets/aliens/portal/summon/portal_alien_summon_frame2.png assets/aliens/portal/summon/portal_alien_summon_frame3.png assets/aliens/portal/summon/portal_alien_summon_frame4.png assets/aliens/portal/summon/portal_alien_summon_frame5.png"^
 portal_idle="assets/portal/idle/portal_idle_frame0.png assets/portal/idle/portal_idle_frame1.png assets/portal/idle/portal_idle_frame2.png assets/portal/idle/portal_idle_frame3.png"^
 portal_close="assets/portal/close/portal_close_frame0.png assets/portal/close/portal_close_frame1.png assets/portal/close/portal_close_frame2.png"